---
- name: Provision a swarm master node
  hosts: "{{ target }}"
  become: yes
  tasks:
      - name: Update apt repository cache
        apt:
            update_cache: yes

      - name: Install dependencies packages
        apt:
            name: "{{ item }}"
            state: present
        with_items:
            - wget
            - curl
            - apt-transport-https
            - gnupg2
            - software-properties-common

      - name: Add docker apt repository key
        apt_key:
            url: https://download.docker.com/linux/debian/gpg
            state: present

      - name: Add docker apt repository
        apt_repository:
            repo: "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
            state: present

      - name: Install docker packages
        apt:
            name: "{{ item }}"
            state: present
        with_items:
            - docker-ce
            - docker-ce-cli
            - containerd.io

      - name: Add vagrant user to docker group
        user:
            name: vagrant
            group: docker

      - name: Disable swapp
        command: sed -i '/swap/d' /etc/fstab

      - name: Disable swap
        command: swapoff -a

      - name: Initiate docker swarm
        command: "docker swarm init --advertise-addr {{ master_ip }}"

      - name: Generate join command
        command: docker swarm join-token --quiet worker
        register: join

      - name: Copy join command to local file
        become: no
        local_action: copy content={{ join.stdout }} dest={{ join_file }}
